INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:24-05-2021-19-23-57
INFO:root:loaded class labels:
INFO:root:water
INFO:root:land
INFO:root:24-05-2021-19-23-57
INFO:root:Folder created: results/results2021-05-24-19-23
INFO:root:24-05-2021-19-23-57
INFO:root:Results will be written to results/results2021-05-24-19-23
INFO:root:24-05-2021-19-23-57
INFO:root:loaded files:
INFO:root:assets/chunk10_m_3507664_nw_18_060_20181013_20190211_multiband-0.jpg
INFO:root:assets/chunk15_m_3407621_nw_18_1_20160911_multiband-2.jpg
INFO:root:assets/chunk17_m_3407607_ne_18_1_20120603_multiband-2.jpg
INFO:root:assets/chunk27_m_3507663_se_18_1_20120603_multiband-2.jpg
INFO:root:assets/chunk55_m_3507664_sw_18_1_20100612_multiband-1.jpg
INFO:root:assets/chunk63_m_3507664_sw_18_1_20120603_multiband-0.jpg
INFO:werkzeug: * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [24/May/2021 19:24:02] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/May/2021 19:24:02] "GET /_dash-layout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/May/2021 19:24:02] "GET /_dash-dependencies HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/May/2021 19:24:02] "GET /_favicon.ico?v=1.12.0 HTTP/1.1" 200 -
INFO:root:24-05-2021-19-24-03
INFO:root:File list written to files_done.txt
INFO:werkzeug:127.0.0.1 - - [24/May/2021 19:24:03] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:root:24-05-2021-19-24-03
INFO:root:File list written to files_done.txt
INFO:werkzeug:127.0.0.1 - - [24/May/2021 19:24:03] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 204 -
INFO:root:24-05-2021-19-24-18
INFO:root:File list written to files_done.txt
INFO:werkzeug:127.0.0.1 - - [24/May/2021 19:24:18] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:root:24-05-2021-19-24-22
INFO:root:File list written to files_done.txt
INFO:werkzeug:127.0.0.1 - - [24/May/2021 19:24:22] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:root:24-05-2021-19-24-23
INFO:root:File list written to files_done.txt
INFO:werkzeug:127.0.0.1 - - [24/May/2021 19:24:23] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:root:24-05-2021-19-24-24
INFO:root:File list written to files_done.txt
INFO:werkzeug:127.0.0.1 - - [24/May/2021 19:24:24] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:root:24-05-2021-19-24-25
INFO:root:File list written to files_done.txt
INFO:werkzeug:127.0.0.1 - - [24/May/2021 19:24:25] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:root:24-05-2021-19-24-27
INFO:root:File list written to files_done.txt
INFO:werkzeug:127.0.0.1 - - [24/May/2021 19:24:27] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:root:24-05-2021-19-24-28
INFO:root:File list written to files_done.txt
INFO:werkzeug:127.0.0.1 - - [24/May/2021 19:24:28] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:root:24-05-2021-19-24-29
INFO:root:File list written to files_done.txt
INFO:werkzeug:127.0.0.1 - - [24/May/2021 19:24:29] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:root:24-05-2021-19-24-30
INFO:root:File list written to files_done.txt
INFO:werkzeug:127.0.0.1 - - [24/May/2021 19:24:30] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:root:24-05-2021-19-24-32
INFO:root:File list written to files_done.txt
INFO:werkzeug:127.0.0.1 - - [24/May/2021 19:24:32] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:root:24-05-2021-19-24-33
INFO:root:File list written to files_done.txt
INFO:root:24-05-2021-19-24-33
INFO:root:Saving RF model to RandomForestClassifier_water_land.pkl.z
INFO:root:24-05-2021-19-24-33
INFO:root:Saving data features to RandomForestClassifier_water_land.pkl.z
ERROR:minimal_doodler_server:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/home/marda/anaconda3/envs/dashdoodler/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/marda/anaconda3/envs/dashdoodler/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/marda/anaconda3/envs/dashdoodler/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/marda/anaconda3/envs/dashdoodler/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/marda/anaconda3/envs/dashdoodler/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/marda/anaconda3/envs/dashdoodler/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/marda/anaconda3/envs/dashdoodler/lib/python3.6/site-packages/dash/dash.py", line 1032, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/home/marda/anaconda3/envs/dashdoodler/lib/python3.6/site-packages/dash/dash.py", line 967, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "minimal_doodler_server.py", line 912, in update_output
    crf_theta_slider_value, crf_mu_slider_value, results_folder, rf_downsample_value, crf_downsample_value, my_id_value, rf_file, data_file, #gt_prob,
NameError: name 'crf_downsample_value' is not defined
INFO:werkzeug:127.0.0.1 - - [24/May/2021 19:24:33] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
